export const products = [   
    {
        id: 1,
        name: "Legion Lenovo",
        description: "A powerful gaming laptop with high-end specs for immersive gaming experiences.",
        image: "https://i.ebayimg.com/images/g/SzIAAOSwA9tj6s6x/s-l1600.jpg",
        price:999.99 + "€" ,
    },
    {
        id: 2,
        name: "iPhone 14 - 128GB",
        description: "The latest iPhone model with 128GB storage for all your multimedia needs.",
        image: "https://imagineonline.store/cdn/shop/files/r1595_Yellow_PDP_Image_Position-1A__en-IN_3b89cb18-d778-42d6-b944-6fbb4c3fb47f_823x.jpg?v=1692352177",
        price:499.99 + "€" ,
    },
    {
        id: 3,
        name: "ANC Wireless Headphones",
        description: "Noise-canceling wireless headphones for an immersive audio experience.",
        image: "https://d3lnc7yu1ksdj.cloudfront.net/wp-content/uploads/2022/08/Hesh-ANC_True-Black_S6HHW-N740_Hero_v001.jpg",
        price:79.99 + "€" ,
    },
    {
        id: 4,
        name: "Gaming PC",
        description: "A high-performance gaming PC for playing the latest games with ease.",
        image: "https://www.awd-it.co.uk/media/catalog/product/x/_/x_air_mesh_arc_pc_2.jpg",
        price:1199.99 + "€" ,
    },
    {
        id: 5,
        name: "Samsung Galaxy Tab",
        description: "A feature-packed tablet for work, entertainment, and productivity on the go.",
        image: "https://static.independent.co.uk/2022/04/07/14/samsung%20galaxy%20tab%20s8.jpg",
        price:299.99+ "€" ,
    },
    {
        id: 6,
        name: "Smartwatch",
        description: "A stylish smartwatch that tracks your fitness and keeps you connected on the move.",
        image: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1666633876-31xSAHViI8L._SL500_.jpg?crop=1xw:1.00xh;center,top&resize=980:*",
        price:149.99+ "€" ,
    },
    {
        id: 7,
        name: "Power bank",
        description: "A portable power bank to keep your devices charged while on the go.",
        image: "https://m.media-amazon.com/images/I/612vaudnEkL.jpg",
        price:29.99+ "€" ,
    },
    {
        id: 8,
        name: "JBL Flip 5 Bluetooth Speaker",
        description: "A portable Bluetooth speaker with high-quality sound for your music and podcasts.",
        image: "https://www.seanhennessy.ie/image/thumbnails/1d/22/JBLFLIP5BLU_jpg-119337-800x800.jpg",
        price:49.99+ "€" ,
    },
    {
        id: 9,
        name: "WD 4TB USB 3.0",
        description: "A high-capacity external hard drive for all your storage needs.",
        image: "https://snpi.dell.com/snp/images/products/large/en-us~AA888500/AA888500.jpg",
        price:89.99+ "€" ,
    },
    {
        id: 10,
        name: "Meta Quest 2 - Advanced All-In-One",
        description: "A virtual reality headset for gaming and immersive experiences.",
        image: "https://media.gamestop.com/i/gamestop/11107421-11107422_ALT01?$pdp$",
        price:199.99+ "€" ,
    },
    {
        id: 11,
        name: "Wireless Keyboard",
        description: "A wireless keyboard for comfortable typing and productivity.",
        image: "https://dorangadget.com/wp-content/uploads/2021/11/keyboard-laptop-keyboard-komputer-keyboard-adalah-harga-keyboard-murah-1-2.jpg",
        price:49.99+ "€" ,
    },
    {
        id: 12,
        name: "In-Ear Earbuds",
        description: "High-quality in-ear earbuds for enjoying music and audio on the go.",
        image: "https://www.mytrendyphone.ie/images/Samsung-Galaxy-Buds-Live-SM-R180NZKAEUE-Mystic-Black-8806090486869-20082020-1-p.webp",
        price:29.99+ "€" ,
    },
    {
        id: 13,
        name: "4K Ultra HD TV",
        description: "A 4K Ultra HD TV for stunning visuals and an immersive viewing experience.",
        image: "https://i0.wp.com/interplast-group.com/wp-content/uploads/2023/09/UE85CU7172.jpg?fit=1000%2C1000&ssl=1",
        price:799.99+ "€" ,
    },
    {
        id: 14,
        name: "Sony ZV-1 Digital Camera (White)",
        description: "A high-quality digital camera for capturing memorable moments in style.",
        image: "https://digitalshopbd.com/public/uploads/all/zu0SfccpNrsj3ln9g4EcrggSsHLRAMrRMNKlrQaR.jpg",
        price:399.99+ "€" ,
    },
    {
        id: 15,
        name: "PS5 Gaming Console",
        description: "The next-gen gaming console for an immersive gaming experience.",
        image: "https://www.pbtech.co.nz/imgprod/G/A/GAMSNY5504__1.jpg",
        price:299.99+ "€" ,
    },
    {
        id: 16,
        name: "Laptop Backpack",
        description: "A durable and stylish backpack designed to carry your laptop and essentials.",
        image: "https://www.rivacase.com/images/virtuemart/product/8365_blue.4260403573181.ver01.jpg",
        price:39.99+ "€" ,
    },
    {
        id: 17,
        name: "Portable Monitor",
        description: "A portable monitor for on-the-go productivity and entertainment.",
        image: "https://m.media-amazon.com/images/I/717-i0yqNzL._AC_UF894,1000_QL80_.jpg",
        price:199.99+ "€" ,
    },
    {
        id: 18,
        name: "Alexa Smart Hub",
        description: "An AI-powered smart hub for controlling your smart home devices.",
        image: "https://adminapi.applegadgetsbd.com/storage/media/large/2563-67586.jpg",
        price:149.99+ "€" ,
    },
    {
        id: 19,
        name: "Black Graphic Tablet, For Laptop",
        description: "A graphic tablet for digital artists and designers to create stunning artwork.",
        image: "https://www.acegizmo.com/wp-content/uploads/2022/05/1105G430.jpg",
        price:149.99+ "€" ,
    },
    {
        id: 20,
        name: "Samsung 34-Inch Ultrawide Monitor",
        description: "A high-resolution ultrawide monitor for multitasking and gaming.",
        image: "https://images.samsung.com/is/image/samsung/ae-curved-cf390-lc34f390fwmxue-lperspectiveblack-126263281?$720_576_PNG$",
        price:499.99+ "€" ,
    },
    {
        id: 21,
        name: "Smart Refrigerator",
        description: "A state-of-the-art smart refrigerator with advanced features and ample storage space for your groceries.",
        image: "https://images.thdstatic.com/productImages/a894ea42-1f5b-4b95-9bf1-c303e3be330b/svn/fingerprint-resistant-stainless-steel-samsung-french-door-refrigerators-rf27t5501sr-64_1000.jpg",
        price:1099.99+ "€" ,
    },
    {
        id: 22,
        name: "Robot Vacuum Cleaner",
        description: "A robot vacuum cleaner that keeps your floors clean and tidy with minimal effort.",
        image: "https://m.media-amazon.com/images/I/61eRk8uocmS.jpg",
        price:249.99+ "€" ,
    },
    {
        id: 23,
        name: "Wireless Router",
        description: "A high-performance wireless router for fast and reliable internet connectivity in your home or office.",
        image: "https://www.linksys.com/on/demandware.static/-/Sites-master-product-catalog/default/dw704bc017/images/hi-res/4/89485812_E5350_left_quarter.jpg",
        price:79.99+ "€" ,
    },
    {
        id: 24,
        name: "Smart Thermostat",
        description: "A smart thermostat that helps you control and optimize your home's heating and cooling systems for energy efficiency.",
        image: "https://m.media-amazon.com/images/I/51YWnoWYbkL.jpg",
        price:129.99+ "€" ,
    },
    {
        id: 25,
        name: "External SSD Drive",
        description: "A high-speed external SSD drive for lightning-fast data transfer and storage capabilities.",
        image: "https://www.ravpower.com/cdn/shop/products/um003.jpg?v=1625749285",
        price:69.99+ "€" ,
    },
    {
        id: 26,
        name: "Microsoft Bluetooth Mouse (Mint) - JB Hi-Fi",
        description: "A stylish and reliable Microsoft Bluetooth mouse for smooth and precise cursor control.",
        image: "https://www.jbhifi.com.au/cdn/shop/products/414439-Product-0-I-637177087606327923_grande.jpg",
        price:19.99+ "€" ,
    },
    {
        id: 27,
        name: "Video Doorbell Pro",
        description: "A high-quality video doorbell for enhancing the security of your home with real-time monitoring and communication.",
        image: "https://cdn.shopify.com/s/files/1/2393/8647/products/ring_video_doorbell_wired_pro_1500x1500_2x_60698235-40cb-4924-a4f8-f84b7cf0ec6a.jpg?v=1678279636",
        price:129.99+ "€" ,
    },
    {
        id: 28,
        name: "Wireless Charging Pad",
        description: "A wireless charging pad for conveniently charging your compatible devices without the need for cables.",
        image: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HPU72?wid=8000&hei=5558&fmt=jpeg&qlt=95&.v=1636763768000",
        price:29.99+ "€" ,
    },
    {
        id: 29,
        name: "SSD SATA 500GB",
        description: "A high-capacity SSD SATA drive for improved storage performance and faster data access.",
        image: "https://m.media-amazon.com/images/I/61I4dVw+HEL.jpg",
        price:119.99+ "€" ,
    },
    {
        id: 30,
        name: "Nintendo Switch (OLED Model) The Legend of Zelda",
        description: "The Nintendo Switch (OLED Model) featuring The Legend of Zelda game for an enhanced gaming experience.",
        image: "https://c1-ebgames.eb-cdn.com.au/merchandising/images/packshots/f654997654674d5996bc54cc2c627c6d_Original.jpg",
        price:549.99+ "€" ,
    },
    {
        id: 31,
        name: "4K Ultra HD Blu-ray Player BDP7501/F7 | Philips",
        description: "A 4K Ultra HD Blu-ray player for enjoying your favorite movies and TV shows in stunning detail and clarity.",
        image: "https://images.philips.com/is/image/PhilipsConsumer/BDP7501_F7-IMS-en_CA?$jpglarge$&wid=1250",
        price:149.99+ "€" ,
    },
    {
        id: 32,
        name: "Xiaomi Wi-Fi Range Extender",
        description: "A Wi-Fi range extender that expands your network coverage for improved connectivity throughout your home or office.",
        image: "https://www.tradeinn.com/f/13758/137584646_2/xiaomi-mi-wifi-range-extender-pro-wifi-repeater.jpg",
        price:39.99+ "€" ,
    },
    {
        id: 33,
        name: "Smartwatch Charger",
        description: "A charger designed for your smartwatch, ensuring it's always ready to go when you are.",
        image: "https://m.media-amazon.com/images/I/51Xba2mO7vL.jpg",
        price:14.99+ "€" ,
    },
    {
        id: 34,
        name: "WHITE SHARK gaming mechanical keyboard",
        description: "A gaming mechanical keyboard with high precision and customizable features for a competitive edge in gaming.",
        image: "https://hyperlift.hr/storage/app/uploads/public/619/73c/02d/61973c02d3339067588327.jpg",
        price:69.99+ "€" ,
    },
    {
        id: 35,
        name: "Wireless Desk Lamp",
        description: "A wireless desk lamp with LED lighting for versatile and convenient illumination in any workspace.",
        image: "https://tghsmart.ie/wp-content/uploads/2020/11/WIRELESS-CHARGING-LAMPS-LED-LIGHTING-1-black.jpg",
        price:34.99+ "€" ,
    },
    {
        id: 36,
        name: "Cloud || - Gaming Headset | Hyper X",
        description: "A gaming headset designed for immersive audio experiences and clear communication during gaming sessions.",
        image: "https://hyperx.com/cdn/shop/files/hyperx_cloud_ii_red_2_main_mixer_2048x2048.jpg?v=1695397316",
        price:119.99+ "€" ,
    }, 
            
    {
    id: 37,
    name: "DJI Mavic Air 2 Drone",
    description: "A high-quality drone with 4K camera and intelligent flight features for capturing stunning aerial photos and videos.",
    image: "https://www1.djicdn.com/cms/uploads/c323a1ef546e5e8b8e15bac5974dc217@374*374.jpg",
    price: 799.99 + "€",
},
{
    id: 38,
    name: "Bose QuietComfort 45 Headphones",
    description: "Premium noise-canceling headphones for the ultimate audio experience and comfortable wear.",
    image: "https://buymobile.co.nz/cdn/shop/products/866724-0400copy_2048x2048.jpg?v=1681897900",
    price: 349.99 + "€",
},
{
    id: 39,
    name: "Canon EOS 5D Mark IV DSLR Camera",
    description: "A professional-grade DSLR camera for high-resolution photography and 4K video recording.",
    image: "https://www.bhphotovideo.com/images/images2000x2000/canon_eos_5d_mark_iv_1274706.jpg",
    price: 2499.99 + "€",
},
{
    id: 40,
    name: "Apple Watch Series 7",
    description: "The latest Apple Watch with a larger display, health tracking features, and more.",
    image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/FKN53?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1647901190267",
    price: 349.99 + "€",
},
{
    id: 41,
    name: "LG OLED 4K Smart TV",
    description: "An OLED TV with stunning picture quality, smart features, and immersive sound.",
    image: "https://btech.com/cdn-cgi/image/quality=50,format=auto/media/catalog/product/cache/020266c7f4c3b5165bc79676a6a3011c/d/z/dz-1_einuf0fevzpbc33u.jpg",
    price: 1499.99 + "€",
},
{
    id: 42,
    name: "Kindle Paperwhite eReader",
    description: "A waterproof eReader for enjoying your favorite books on the go with a high-resolution display.",
    image: "https://m.media-amazon.com/images/G/01/kindle/journeys/5xlDnKG94P0ryVnD8MqFmnIhMKBXE2F2BxyzUQHa63Hhs3D/ZjBjZWUxMjIt._CB641064212_.jpg",
    price: 129.99 + "€",
},
{
    id: 43,
    name: "Samsung 27-Inch Curved Gaming Monitor",
    description: "A curved gaming monitor with fast refresh rates and vibrant colors for an immersive gaming experience.",
    image: "https://m.media-amazon.com/images/I/71VgOLPRgkL.jpg",
    price: 299.99 + "€",
},
{
    id: 44,
    name: "Fujifilm Instax Mini 11 Instant Camera",
    description: "An instant camera for capturing and printing memorable photos in seconds.",
    image: "https://media.extra.com/s/aurora/100195535_800/Fujifilm-Instax-Mini-11-Instant-Film-Camera%2C-Blush-Pink?locale=en-GB,en-*,*&$Listing-Product-2x$",
    price: 69.99 + "€",
},
{
    id: 45,
    name: "Samsung Galaxy S22",
    description: "The latest Samsung Galaxy smartphone with advanced camera features and powerful performance.",
    image: "https://cdn.dxomark.com/wp-content/uploads/medias/post-112063/Samsung-Galaxy-S22-Ultra-Snapdragon_-featured-image-packshot-review-Recovered.jpg",
    price: 799.99 + "€",
},
{
    id: 46,
    name: "Logitech G Pro X Mechanical Gaming Keyboard",
    description: "A mechanical gaming keyboard with customizable switches and RGB lighting for competitive gaming.",
    image: "https://ecommerce.datablitz.com.ph/cdn/shop/products/4_5cccc010-a675-4d25-b45e-dfc56930066e_1024x.jpg?v=1679964525",
    price: 129.99 + "€",
},
{
    id: 47,
    name: "Google Nest Hub Max",
    description: "A smart display with Google Assistant for controlling your smart home and staying connected.",
    image: "https://www.bhphotovideo.com/images/images2500x2500/google_ga00639_us_nest_hub_max_charcoal_1499419.jpg",
    price: 229.99 + "€",
},
{
    id: 48,
    name: "Nikon D850 DSLR Camera",
    description: "A high-resolution DSLR camera with exceptional image quality and professional features.",
    image: "https://m.media-amazon.com/images/I/81XyyEsFS7L.jpg",
    price: 2999.99 + "€",
},
{
    id: 49,
    name: "Bose SoundLink Revolve+ Bluetooth Speaker",
    description: "A portable Bluetooth speaker with 360-degree sound and long-lasting battery life.",
    image: "https://m.media-amazon.com/images/I/81To0nRciPL.jpg",
    price: 199.99 + "€",
},
{
    id: 50,
    name: "Nintendo Switch Pro Controller",
    description: "A high-quality controller for the Nintendo Switch, designed for a comfortable gaming experience.",
    image: "https://i5.walmartimages.com/seo/Nintendo-Switch-Pro-Controller_7a20f413-2f9e-46c9-9b5f-8cdb32d125cc_1.1f0a2f6313f2fb2cd3c42f4566f44506.jpeg",
    price: 69.99 + "€",
},
{
    id: 51,
    name: "Dell Ultrasharp 27-inch Monitor",
    description: "A high-quality 27-inch monitor for professional work and stunning visual clarity.",
    image: "https://m.media-amazon.com/images/I/71YqpUwrpBL.jpg",
    price: 449.99 + "€",
},
{
    id: 52,
    name: "Sony WH-1000XM4 Wireless Headphones",
    description: "Premium wireless headphones with noise-canceling technology and exceptional audio quality.",
    image: "https://i5.walmartimages.com/seo/Sony-WH-1000XM4-Wireless-Noise-Canceling-Over-the-Ear-Headphones-with-Google-Assistant-Black_0dfeda7b-df98-488a-a190-67b54d2fb40d.2bc50af0f21a464edd51076af3c85e92.jpeg",
    price: 299.99 + "€",
},
{
    id: 53,
    name: "MacBook Pro 16-inch",
    description: "A powerful 16-inch MacBook Pro with a stunning Retina display and high-end performance.",
    image: "https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/refurb-mbp16-space-m1-2021?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1643239951000",
    price: 2399.99 + "€",
},
{
    id: 54,
    name: "GoPro HERO10 Black",
    description: "The latest GoPro action camera with 5.3K video recording and advanced stabilization.",
    image: "https://www.bhphotovideo.com/images/images2500x2500/gopro_chdhx_101_hero10_black_1658382.jpg",
    price: 499.99 + "€",
},
{
    id: 55,
    name: "Bose Home Speaker 500",
    description: "A smart home speaker with voice control and room-filling sound.",
    image: "https://m.media-amazon.com/images/I/81g8ke3f4gL.jpg",
    price: 349.99 + "€",
},
{
    id: 56,
    name: "DJI Mini 2 Drone",
    description: "An ultra-compact drone with 4K camera and enhanced flight features for aerial photography.",
    image: "https://m.media-amazon.com/images/I/51KA0bQmPDL.jpg",
    price: 449.99 + "€",
},
{
    id: 57,
    name: "Samsung Odyssey G7 Gaming Monitor",
    description: "A curved gaming monitor with QLED technology and rapid refresh rates for gaming enthusiasts.",
    image: "https://www.awd-it.co.uk/media/catalog/product/d/o/download_293.png?optimize=high&bg-color=255,255,255&fit=bounds&height=680&width=680&canvas=680:680&format=jpeg",
    price: 799.99 + "€",
},
{
    id: 58,
    name: "Canon EOS R6 Mirrorless Camera",
    description: "A mirrorless camera with 4K video capabilities and advanced autofocus for photography and videography.",
    image: "https://cdn.abdulwahed.com/media/catalog/product/cache/f84b542cb21efc3b3973b50c68d61246/e/o/eos-r6-1.jpg",
    price: 2499.99 + "€",
},
{
    id: 59,
    name: "Apple iPad Air (4th Generation)",
    description: "A sleek and powerful iPad with a liquid retina display and performance to match.",
    image: "https://m.media-amazon.com/images/I/71WpEnDZyNL.jpg",
    price: 599.99 + "€",
},
{
    id: 60,
    name: "Sony PlayStation 5",
    description: "The next-gen gaming console for immersive gaming experiences and stunning graphics.",
    image: "https://media.direct.playstation.com/is/image/sierialto/PS5-front-with-dualsense",
    price: 499.99 + "€",
},
{
    id: 61,
    name: "Samsung Galaxy Z Fold 3",
    description: "A foldable smartphone with a large display and versatile functionality.",
    image: "https://image-us.samsung.com/us/smartphones/galaxy-z-fold3-5g/gallery/green/Gallery-Q2-MainKV_Foldunfold_Green-1600x1200.jpg",
    price: 1799.99 + "€",
},
{
    id: 62,
    name: "Garmin Fenix 7 Multisport Watch",
    description: "A premium multisport watch with advanced fitness and navigation features.",
    image: "https://res.garmin.com/transform/image/upload/b_rgb:FFFFFF,c_pad,dpr_2.0,f_auto,h_400,q_auto,w_400/c_pad,h_400,w_400/v1/Product_Images/en/products/010-02540-00/v/pd-01-xl-a09435ec-1968-47b5-8d12-341eed5e61cd?pgw=1",
    price: 699.99 + "€",
},
{
    id: 63,
    name: "Dell XPS 13 Laptop",
    description: "An ultra-portable laptop with a stunning InfinityEdge display and powerful performance.",
    image: "https://zurimall.co.ke/wp-content/uploads/2022/12/Artboard-2-30.jpg",
    price: 1299.99 + "€",
},
{
    id: 64,
    name: "Logitech G Pro Wireless Gaming Mouse",
    description: "A wireless gaming mouse with ultra-precise sensors and customizable buttons for competitive gaming.",
    image: "https://m.media-amazon.com/images/I/51ySu55JzAL.jpg",
    price: 149.99 + "€",
},
{
    id: 65,
    name: "Fitbit Versa 3 Smartwatch",
    description: "A smartwatch with built-in GPS and health tracking features for an active lifestyle.",
    image: "https://m.media-amazon.com/images/I/51uHD-x+3-L.jpg",
    price: 199.99 + "€",
},
{
    id: 66,
    name: "Anker PowerCore Portable Charger",
    description: "A high-capacity portable charger for keeping your devices powered on the go.",
    image: "https://m.media-amazon.com/images/I/61Fs2NAB7CL.jpg",
    price: 49.99 + "€",
},
{
    id: 67,
    name: "Razer BlackWidow Elite Mechanical Keyboard",
    description: "A mechanical gaming keyboard with customizable RGB lighting and dedicated media controls.",
    image: "https://m.media-amazon.com/images/I/81oLMQUj4fL.jpg",
    price: 159.99 + "€",
},
{
    id: 68,
    name: "Epson EcoTank ET-2760 Wireless Printer",
    description: "A wireless printer with refillable ink tanks for cost-effective and high-quality printing.",
    image: "https://mediaserver.goepson.com/ImConvServlet/imconv/0422c5e5c550703c51a2e3d4e616394da5a206d5/1200Wx1200H?use=banner&hybrisId=B2C&assetDescr=et-2760_dimensions_690x460",
    price: 349.99 + "€",
},
{
    id: 69,
    name: "Xbox Series X Gaming Console",
    description: "The next-gen Xbox console for powerful gaming performance and a vast library of games.",
    image: "https://m.media-amazon.com/images/I/51ojzJk77qL.jpg",
    price: 499.99 + "€",
},
{
    id: 70,
    name: "Nest Learning Thermostat",
    description: "A smart thermostat that learns your preferences and optimizes your home's energy usage.",
    image: "https://lh3.googleusercontent.com/q_kyr_KwKHFr_IzfbD4f_D9WYynR7-nqKfZ2Um8LH0yTSc81cKBmjHbwiTYwvri9C88EU8Bb7uj341zUWpXDbvR0vOkFRCwUKww=rw-e365-nu-w1182",
    price: 219.99 + "€",
},
{
    id: 71,
    name: "ASUS ROG Strix G15 Gaming Laptop",
    description: "A high-performance gaming laptop with a fast refresh rate display and powerful GPU.",
    image: "https://m.media-amazon.com/images/I/81fZmxBbQgL.jpg",
    price: 1499.99 + "€",
},
{
    id: 72,
    name: "Nikon Z6 Mirrorless Camera",
    description: "A versatile mirrorless camera with 4K video capabilities and advanced photography features.",
    image: "https://m.media-amazon.com/images/I/91UQAYF2zBL.jpg",
    price: 1799.99 + "€",
},
{
    id: 73,
    name: "Bowers & Wilkins PX7 Wireless Headphones",
    description: "Premium wireless headphones with adaptive noise canceling and high-quality audio.",
    image: "https://m.media-amazon.com/images/I/61uWghcQ6pL.jpg",
    price: 399.99 + "€",
},
{
    id: 74,
    name: "Canon PIXMA Pro-100 Wireless Printer",
    description: "A professional photo printer for producing high-quality prints with exceptional color accuracy.",
    image: "https://i.pcmag.com/imagery/reviews/05Dl0CvUhgND2thyQWK5AHq-3.fit_lim.size_1050x591.v1569473620.jpg",
    price: 349.99 + "€",
},
{
    id: 75,
    name: "Microsoft Surface Laptop 4",
    description: "A sleek and powerful laptop with a high-resolution PixelSense touchscreen display.",
    image: "https://m.media-amazon.com/images/I/71p-M3sPhhL.jpg",
    price: 1199.99 + "€",
},
{
    id: 76,
    name: "LG CX 4K OLED TV",
    description: "A 4K OLED TV with deep blacks and stunning colors for an immersive viewing experience.",
    image: "https://media.us.lg.com/transform/ecomm-PDPGallery-1100x730/42e5394e-7250-4d5e-9ed2-03d618545268/md07501037-large01-jpg",
    price: 2499.99 + "€",
},
{
    id: 77,
    name: "Sonos Beam Soundbar",
    description: "A compact soundbar for enhancing your home theater audio with voice control and streaming capabilities.",
    image: "https://m.media-amazon.com/images/I/61bJ59nkmaL.jpg",
    price: 399.99 + "€",
},
{
    id: 78,
    name: "OnePlus 9 Pro 5G Smartphone",
    description: "A 5G smartphone with a high-refresh-rate display and a versatile camera system.",
    image: "https://dakauf.eu/wp-content/uploads/2022/10/Oneplus-9-pro_black.jpg",
    price: 699.99 + "€",
},
{
    id: 79,
    name: "Sony A7 III Mirrorless Camera",
    description: "A full-frame mirrorless camera with advanced features for both photography and videography.",
    image: "https://www.bhphotovideo.com/images/images2500x2500/sony_ilce_7m3k_b_alpha_a7_iii_mirrorless_1394219.jpg",
    price: 1999.99 + "€",
},
{
    id: 80,
    name: "GoPro HERO9 Black",
    description: "The HERO9 Black action camera with 5K video recording and advanced stabilization.",
    image: "https://m.media-amazon.com/images/I/81Szbr4wo5L._AC_UF1000,1000_QL80_.jpg",
    price: 549.99 + "€",
},
{
    id: 81,
    name: "Apple AirPods Max",
    description: "High-fidelity over-ear headphones with spatial audio and active noise canceling.",
    image: "https://hips.hearstapps.com/hmg-prod/images/hdm-airpodsmax-046-1647967194.jpg",
    price: 549.99 + "€",
},
{
    id: 82,
    name: "Lenovo ThinkPad X1 Carbon",
    description: "An ultra-light and durable business laptop with a high-resolution display and powerful performance.",
    image: "https://m.media-amazon.com/images/I/71IdnLez7TL.jpg",
    price: 1699.99 + "€",
},
{
    id: 83,
    name: "Fitbit Charge 5 Fitness Tracker",
    description: "A fitness tracker with built-in GPS and health insights for an active lifestyle.",
    image: "https://m.media-amazon.com/images/I/41MOVNsGMbL.jpg",
    price: 129.99 + "€",
},
{
    id: 84,
    name: "Dell Alienware Aurora Gaming Desktop",
    description: "A high-performance gaming desktop with customizable lighting and powerful components.",
    image: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/desktops/alienware-desktops/alienware-aurora-r15-intel/media-gallery/lunar-light-liquid-clear-panel/desktop-alienware-aurora-r15-white-liquid-clear-panel-gallery-1.psd?fmt=pjpg&pscan=auto&scl=1&wid=3525&hei=3941&qlt=100,1&resMode=sharp2&size=3525,3941&chrss=full&imwidth=5000",
    price: 2199.99 + "€",
},
{
    id: 85,
    name: "Epson EcoTank ET-3760 Wireless Printer",
    description: "A wireless printer with refillable ink tanks for cost-effective and high-quality printing.",
    image: "https://mediaserver.goepson.com/ImConvServlet/imconv/2324351e582ca7c75fde5d968ef2d22296fa98f2/1200Wx1200H?use=banner&hybrisId=B2C&assetDescr=ET-3850_white_left_690x460",
    price: 449.99 + "€",
},
{
    id: 86,
    name: "Bose QuietComfort 45 Wireless Headphones",
    description: "Wireless noise-canceling headphones with premium audio and long-lasting comfort.",
    image: "https://m.media-amazon.com/images/I/61+lhpMw+2L.jpg",
    price: 349.99 + "€",
},
{
    id: 87,
    name: "Xiaomi Mi Electric Scooter Pro 2",
    description: "An electric scooter with a long-range battery and foldable design for easy transportation.",
    image: "https://voltride.com/wp-content/uploads/2021/11/3322_61682d38decdc8.27054005_Xiaomi%20Pro2.jpeg",
    price: 599.99 + "€",
},
{
    id: 88,
    name: "Google Nest Hub (2nd Gen)",
    description: "A smart display with Google Assistant for controlling your smart home and accessing information.",
    image: "https://i5.walmartimages.com/seo/Google-Nest-Hub-2nd-Gen-Smart-Home-Display-with-Google-Assistant-Charcoal_40cbd2aa-47a6-4830-a0c7-948786313c99.9aadc58b85ace69c49c940a46625e5ab.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
    price: 99.99 + "€",
},
{
    id: 89,
    name: "Roku Ultra Streaming Player",
    description: "A 4K streaming player with enhanced remote for accessing a wide range of streaming services.",
    image: "https://m.media-amazon.com/images/I/61hpvCuXhpL.jpg",
    price: 89.99 + "€",
},
{
    id: 90,
    name: "HP Envy 27-inch 4K Monitor",
    description: "A 4K monitor with a slim design and vibrant colors for professional and entertainment use.",
    image: "https://m.media-amazon.com/images/I/71g7udGpIKL.jpg",
    price: 499.99 + "€",
},
{
    id: 91,
    name: "Anker SoundCore Mini Portable Speaker",
    description: "A compact and portable Bluetooth speaker with impressive audio quality.",
    image: "https://m.media-amazon.com/images/I/61wAT1GacuL.jpg",
    price: 29.99 + "€",
},
{
    id: 92,
    name: "Samsung Galaxy Watch 4",
    description: "A smartwatch with fitness tracking and health monitoring features.",
    image: "https://target.scene7.com/is/image/Target/GUEST_7e8117d1-45a3-4207-bd31-bfa6bbfbba10",
    price: 249.99 + "€",
},
{
    id: 93,
    name: "DJI Air 2S Drone",
    description: "A compact drone with a high-resolution camera and intelligent flight features.",
    image: "https://m.media-amazon.com/images/I/516rOonY4GL.jpg",
    price: 999.99 + "€",
},
{
    id: 94,
    name: "Logitech C920 HD Pro Webcam",
    description: "A high-definition webcam for video conferencing and streaming.",
    image: "https://www.qqestore.com/magento/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/o/logitech_c920_1.jpg",
    price: 79.99 + "€",
},
{
    id: 95,
    name: "Ultimate Ears BOOM 3 Portable Speaker",
    description: "A portable Bluetooth speaker with 360-degree sound and water resistance.",
    image: "https://m.media-amazon.com/images/I/91ZHcTf0adL.jpg",
    price: 129.99 + "€",
},
{
    id: 96,
    name: "Corsair K95 RGB Platinum XT Mechanical Keyboard",
    description: "A premium mechanical gaming keyboard with customizable RGB lighting and macro keys.",
    image: "https://m.media-amazon.com/images/I/7193Jl8PejL.jpg",
    price: 169.99 + "€",
},
{
    id: 97,
    name: "Nest Cam Indoor Security Camera",
    description: "An indoor security camera for monitoring your home with 24/7 live video and alerts.",
    image: "https://snpi.dell.com/snp/images/products/large/en-us~AC006551/AC006551.jpg",
    price: 199.99 + "€",
},
{
    id: 98,
    name: "Xbox Wireless Controller",
    description: "A wireless controller for Xbox gaming with textured grips and custom button mapping.",
    image: "https://m.media-amazon.com/images/I/51JCqvlkqVL.jpg",
    price: 59.99 + "€",
},
{
    id: 99,
    name: "Lenovo Legion Y27gq-20 Gaming Monitor",
    description: "A high-refresh-rate gaming monitor with NVIDIA G-SYNC for smooth and immersive gameplay.",
    image: "https://1pc.co.il/images/thumbs/0002947_-lenovo-legion-y27q-20-27-inch-led-ips_510.jpeg",
    price: 549.99 + "€",
},
{
    id: 100,
    name: "Canon EF 70-200mm f/2.8L IS III USM Lens",
    description: "A professional telephoto lens for Canon DSLR cameras with advanced optics and image stabilization.",
    image: "https://www.bhphotovideo.com/images/images2000x2000/canon_3044c002_ef_70_200mm_f_2_8l_is_1414599.jpg",
    price: 2199.99 + "€",
},
];


export function composeProduct(products, limit = null) {
    const data = (limit == null) ? products : products.slice(0, limit);
    const container = document.getElementById('contt'); 
  
    for (let product of data) {
      const card = document.createElement('div');
      card.classList.add('card', 'p-2', 'g-col-6', 'prr');
      card.style.width = '17rem';
  
      card.innerHTML = `
        <img src="${product.image}" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">${product.name}</h5>
          <hr>
          <p>${product.description}</p>
          <a href="#" class="btn btn-outline-light">${product.price}</a>
          <button class="btn btn-outline-light add-to-cart" data-product='${JSON.stringify(product)}'><i class="fa-solid fa-shopping-cart" id="cartbtn"></i></button>
          <hr>
          <a href="" class="btn btn-outline-light" style="width: 100%;">Order</a>
        </div>
      `;
  
      const addToCartButton = card.querySelector('.add-to-cart');
      addToCartButton.addEventListener('click', addToCartClicked);
  
      container.appendChild(card);
    }
  }
//   Funksjoni per me shtu ne korp
  function addToCartClicked(event) {
    const productData = JSON.parse(event.currentTarget.getAttribute('data-product'));
  
    const cart = JSON.parse(localStorage.getItem('cart')) || [];
  
    cart.push(productData);
  
    localStorage.setItem('cart', JSON.stringify(cart));
  
    alert('Product added to cart.');
  }